document.write('<div id="tts"><div><span>VOZ</span> <select id="vozSelect" style="margin-bottom:0.6rem;height:auto;"></select></div><div><span>VELOCIDADE</span><input type="range" id="velocidade" min="0.5" max="2" step="0.1" value="1" style="width:100px"><span id="velocidadeValor">1.0x</span> <button id="btnFalar">🔊 Ler</button> <button id="btnParar" style="display:none;">⏸️ Pausar</button></div></div><div id="aba" align="center">ÁUDIO</div>\
<style>#tts{font-size:1.02rem; background-color:#bacff0; border-radius:0 0 17px 0; padding:15px 7px 0 7px; width:90%; margin-left:3%; margin-top:-89px; transition:margin-top 0.3s ease; } #aba{font-size:1rem; font-weight:bold; background-color:#bacff0; border-radius:0 0 12px 12px; padding:9px; width:60px; margin-left:3%; cursor:pointer;} #tts div{display:flex;align-items:center; align-items:center; justify-content:center} #tts div span,#tts div input{margin:0 3px} #tts button{height:30px;line-height:30px; background-color:#1a4798; padding:0 13px; font-size:1.2rem; font-weight:400; margin-left:9px}</style>\
<script>let vozesDisponiveis = [];let utterance;let isSpeaking = false;let vozSelecionada = null;let velocidade = 1;    function esperarVozesDisponiveis(callback) {  let tentativas = 0;     const intervalo = setInterval(() => { vozesDisponiveis = speechSynthesis.getVoices();  if (vozesDisponiveis.length !== 0 || tentativas > 10) { clearInterval(intervalo); callback();  }  tentativas++; }, 200);}\
function carregarVozes() { const select = document.getElementById(\'vozSelect\'); select.innerHTML = '';  vozesDisponiveis.forEach((voz, index) => { const option = document.createElement(\'option\'); option.value = index; option.textContent = `${voz.name} (${voz.lang})`;   select.appendChild(option); }); if (vozesDisponiveis.length > 0) { vozSelecionada = vozesDisponiveis[0];  } } esperarVozesDisponiveis(() => { carregarVozes(); });    speechSynthesis.onvoiceschanged = () => {esperarVozesDisponiveis(carregarVozes); };\
function falarTexto() { if (isSpeaking) return;  const texto = document.getElementById(\'ttscont\').textContent; utterance = new SpeechSynthesisUtterance(texto); utterance.voice = vozSelecionada; utterance.rate = velocidade; utterance.onend = () => { isSpeaking = false; toggleBotoes();}; speechSynthesis.speak(utterance); isSpeaking = true; toggleBotoes();}\
function pausarOuContinuar() { if (speechSynthesis.speaking && !speechSynthesis.paused) {  speechSynthesis.pause(); document.getElementById(\'btnParar\').textContent = '▶️ Continuar'; } else { speechSynthesis.resume(); document.getElementById(\'btnParar\').textContent = \'⏸️ Pausar\'; }}\
document.getElementById(\'velocidade\').addEventListener(\'input\', function () { velocidade = parseFloat(this.value); document.getElementById(\'velocidadeValor\').textContent = velocidade;  if (isSpeaking) {  speechSynthesis.cancel(); isSpeaking = false; falarTexto(); } });\
document.getElementById(\'vozSelect\').addEventListener(\'change\', function () { const index = parseInt(this.value); vozSelecionada = vozesDisponiveis[index]; if (isSpeaking) { speechSynthesis.cancel(); isSpeaking = false; falarTexto(); } });\
document.getElementById(\'btnFalar\').addEventListener(\'click\', falarTexto); document.getElementById(\'btnParar\').addEventListener(\'click\', pausarOuContinuar);\
function toggleBotoes() { const falando = speechSynthesis.speaking && !speechSynthesis.paused; document.getElementById(\'btnFalar\').style.display = falando ? "none" : "inline-block";  document.getElementById(\'btnParar\').style.display = falando || speechSynthesis.paused ? "inline-block" : "none"; document.getElementById(\'btnParar\').textContent = \'⏸️ Pausar\'; }\
window.addEventListener("beforeunload", () => {  speechSynthesis.cancel(); });\
const abaElement = document.getElementById(\'aba\'); const ttsElement = document.getElementById(\'tts\'); let isMarginZero = false; abaElement.addEventListener('click', function() { if (isMarginZero) { ttsElement.style.marginTop = \'-89px\'; } else { ttsElement.style.marginTop = \'0\';  }  isMarginZero = !isMarginZero;  });</script>');
